image: node:4

stages:
    - test
    - package
    - notify

test:
    tags:
        - docker-executor
    stage: test
    except:
        - triggers
    script:
        - npm install
        - npm test

package:
    tags:
        - docker-executor
    stage: package
    only:
        - /^release-.*/
        - /^hf-.*/
    script:
        - npm run package -- --no-deps
    artifacts:
        name: ${CI_PROJECT_NAME}-${CI_BUILD_REF}
        paths:
            - dist/
            - doc/

notify:
    tags:
        - docker-executor
    stage: notify
    except:
        - master
    script:
        - if [[ "$AUTO_NOTIFY" == true ]]; then
        -     echo 'Running notifyProjects.sh'
        -     ./build/notifyProjects.sh
        - else
        -     echo AUTO_NOTIFY is off, skipping notification.
        - fi