image: node:6

stages:
    - test
    - package
    - publish
    - notify

test_node4:
    image: node:4
    tags:
        - docker-executor
    stage: test
    except:
        - triggers
    script:
        - npm install --global npm@5.10.0
        - npm ci --registry ${NPM_REGISTRY}
        - npm install --registry ${NPM_REGISTRY} @f5devcentral/f5-cloud-libs@beta
        - npm install mocha@5.2.0
        - npm install nyc@11.1.0
        - npm install yargs@11.1.1
        - npm run lint
        - npm test

test_node6:
    image: node:6
    tags:
        - docker-executor
    stage: test
    except:
        - triggers
    script:
        - npm install --registry ${NPM_REGISTRY}
        - npm install --registry ${NPM_REGISTRY} --no-save @f5devcentral/f5-cloud-libs@beta
        - npm install mocha@5.2.0
        - npm install nyc@14.0.0
        - npm run lint
        - npm test

test_node8:
    image: node:8
    tags:
        - docker-executor
    stage: test
    except:
        - triggers
    script:
        - npm ci --registry ${NPM_REGISTRY}
        - npm install --registry ${NPM_REGISTRY} --no-save @f5devcentral/f5-cloud-libs@beta
        - npm run lint
        - npm test

# audit packages for vulnerabilities
test_audit:
    image: node:8
    stage: test
    script:
        # npm audit - uses custom audit processor wrapper
        - npm ci
        - npm run audit
    tags:
        - cm-official-docker-executor
    except:
        - triggers

package:
    tags:
        - docker-executor
    stage: package
    only:
        - /^release-.*/
        - /^hf-.*/
    script:
        - npm run package -- --production
    artifacts:
        name: ${CI_PROJECT_NAME}-${CI_BUILD_REF}
        paths:
            - dist/
            - doc/

publish:
    tags:
        - docker-executor
    stage: publish
    only:
        - master
    script:
        - npm install npm@latest -g --registry ${NPM_REGISTRY}
        - echo '//registry.npmjs.org/:_authToken="${NPM_TOKEN}"' > ./.npmrc
        - npm publish --access public --tag experimental

notify:
    tags:
        - docker-executor
    stage: notify
    except:
        - master
    script:
        - if [[ "$AUTO_NOTIFY" == true ]]; then
        -     echo 'Running notifyProjects.sh'
        -     ./build/notifyProjects.sh
        - else
        -     echo AUTO_NOTIFY is off, skipping notification.
        - fi
